version: '3.3'

services:
  cron:
    build:
      context: docker/cron
      dockerfile: Dockerfile 
    image: ayoubensalem/magento1-cron
    depends_on:
      - apache
      - varnish
    networks:
      - appnet
    volumes:
      - magento_data:/var/www/html
      - ./varnish.secret:/varnish.secret
 #     - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  ssl:
    image: fballiano/nginx-ssl-for-magento2
    depends_on:
      - varnish
    networks:
      - appnet
    ports:
      - "443:443"

  varnish:
    image: fballiano/varnish
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    networks:
      - appnet 
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: ayoubensalem/magento1-app
    depends_on:
      - master
      - redis
      - redis-cache
      - cache
      - clusterdata
    networks:
      - appnet
    volumes:
      - magento_data:/var/www/html
      - ~/.composer/auth.json:/root/.composer/auth.json
#      - ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  master:
    hostname: 'master'
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=19641995
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=19641995
      - MYSQL_DATABASE=magento
    ports:
      - "3306:3306"
    networks:
      - appnet 
 
  
  redis-cache: 
    image: redis
    networks:
      - appnet 

  redis: 
    image: redis
    networks:
      - appnet 


  cache: 
    image: fballiano/redis-volatile
    networks:
      - appnet 

  clusterdata:
    image: fballiano/redis-volatile
    networks: 
      - appnet 


networks:
  appnet:
    driver: bridge
volumes:
  magento_data:
