version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: ayoubensalem/magento1-app
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.composer/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    # volumes:
    #   - dbdata:/var/lib/mysql
    networks:
      - appnet
    environment:
      - MYSQL_ROOT_PASSWORD=19641995
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=19641995


networks:
  appnet:
    driver: bridge
# volumes:
#   dbdata:
