--- # Playbook for setting up swarm cluster 10.42.2.180
- name: Init Swarm Master
  hosts: local
  gather_facts: False
  remote_user: root
  tasks:
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}
      ignore_errors: yes

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      ignore_errors: yes
      register: worker_token

    - name: Show Worker Token
      debug: var=worker_token.stdout

    - name: Master Token
      command: docker swarm join-token manager -q
      ignore_errors: yes
      register: master_token

    - name: Show Master Token
      debug: var=master_token.stdout

- name: Join Swarm Cluster
  hosts: slaves
  remote_user: root
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['local'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['local'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      ignore_errors: yes
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr

