apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-rook-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
kind: Service
apiVersion: v1
metadata:
  name: apache
spec:
  ports:
    - name: apache-port
      port: 80
      targetPort: 80
  selector:
    app: apache
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ayoubensalem/magento1-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: apachee-data
      restartPolicy: Always
      volumes:
      - name: apachee-data
        persistentVolumeClaim:
          claimName: apache-rook-pvc
  