apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
kind: Service
apiVersion: v1
metadata:
  name: redis-cache
spec:
  ports:
    - name: cache-port
      port: 6379
      targetPort: 6379
  selector:
    app: redis-cache
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: cache-port
        volumeMounts:
        - mountPath: /data
          name: cache-data
      restartPolicy: Always
      volumes:
      - name: cache-data
        persistentVolumeClaim:
          claimName: cache-pvc 
  