apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
kind: Service
apiVersion: v1
metadata:
  name: clusterdata
spec:
  ports:
    - name: clusterdata-port
      port: 6379
      targetPort: 6379
  selector:
    app: clusterdata
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterdata
  template:
    metadata:
      labels:
        app: clusterdata
    spec:
      containers:
      - name: clusterdata
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: cluster-data
      restartPolicy: Always
      volumes:
      - name: cluster-data
        persistentVolumeClaim:
          claimName: clusterdata-pvc 
  