kind: Service
apiVersion: v1
metadata:
  name: cron
spec:
  selector:
    app: cron
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: ayoubensalem/magento1-cron
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/www/html
          name: cron-data
      restartPolicy: Always
      volumes:
      - name: cron-data
        persistentVolumeClaim:
          claimName: apache-pvc  