apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbCreds
              key: rootPassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbCreds
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: dbCreds
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dbCreds
              key: username
        ports:
        - containerPort: 3306
      restartPolicy: Always
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql_data
  volumes:
  - name: mysql_data
    flexVolume:
      driver: rexray/dobs
