kind: Service
apiVersion: v1
metadata:
  name: nginx-ssl
spec:
  ports:
    - name: nginx-port
      port: 443
      targetPort: 443
  selector:
    app: nginx-ssl
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ssl
  template:
    metadata:
      labels:
        app: nginx-ssl
    spec:
      containers:
      - name: nginx-ssl
        image: nginx:stable-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: varnish
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      restartPolicy: Always
