apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
    - name: session-port
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: session-port
        volumeMounts:
        - mountPath: /data
          name: session-data
      restartPolicy: Always
      volumes:
      - name: session-data
        persistentVolumeClaim:
          claimName: session-pvc 