kind: Service
apiVersion: v1
metadata:
  name: varnish
spec:
  ports:
    - name: varnish-port
      port: 80
      targetPort: 80
    - name: varnal-port
      port: 6082
      targetPort: 6082
  selector:
    app: apache
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - name: varnish
        image: ayoubensalem/magento1-varnish
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: varinsh-port
        - containerPort: 6082
          name: varnal-port
        livenessProbe:
          httpGet:
            path: apache
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      restartPolicy: Always
